### ISSUE TITLE
Cannot reopen Blockly component with custom theme

### ISSUE THREAD

**Issue by kajetanoss123** [roroettg/ngx-blockly#32] opened 2020-12-03 14:34 UTC
When I use a custom theme, initializing it like so:
`config: NgxBlocklyConfig = {
...
theme: exampleTheme.createBlocklyTheme()
`
and the theme:

```
export const blockStyles: BlockStyles = {
    logic_blocks: {
        colourPrimary: '#997710',
    },
    math_blocks: {
        colourPrimary: '#521f73',
    },
    control_blocks: {
        colourPrimary: '#005a16',
    }
};
export const categoryStyles: CategoryStyles = {
    logic_category: {
        colour: '#997710',
    },
    math_category: {
        colour: '#521f73',
    },
    control_category: {
        colour: '#005a16',
    },
};
export const componentStyle: ComponentStyle = {
    workspaceBackgroundColour: '#2c2c2c',
    toolboxBackgroundColour: '#3d3d3d',
    scrollbarColour: '#ba131b',
    insertionMarkerColour: '#2fff00',
    insertionMarkerOpacity: 0.2,
    flyoutBackgroundColour: '#2e2e2e',
    flyoutOpacity: 1
};
export const exampleTheme: Theme = new Theme (
    'ThemeName',
    blockStyles,
    categoryStyles,
    componentStyle
);
```

I can only open it once. When I go to another component and go back I'm receiving a following message:

ERROR Error: Uncaught (in promise): Error: Name "themename" with type "theme" already registered.
Error: Name "themename" with type "theme" already registered.
    at Object.Blockly.registry.register (blockly_compressed.js:18)
    at new Blockly.Theme (blockly_compressed.js:127)
    at Theme.createBlocklyTheme (ngx-blockly.js:630)
    at new CompleteScriptUpdateComponent (complete-script-update.component.ts:133)
    at NodeInjectorFactory.CompleteScriptUpdateComponent_Factory [as factory] (complete-script-update.component.ts:309)
    at getNodeInjectable (core.js:4274)
    at instantiateRootComponent (core.js:7972)
    at createRootComponent (core.js:13488)
    at ComponentFactory$1.create (core.js:24047)
    at ViewContainerRef.createComponent (core.js:10151)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27492)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at drainMicroTaskQueue (zone-evergreen.js:569)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484)
    at invokeTask (zone-evergreen.js:1621)

**Comment by roroettg** [comment] 2020-12-09 17:33
I tried to reproduce your error and was not able to reproduce it. Could you give a more detailed example on how you switch Components?

For now I guess the error pretty much explains what is happening. You are adding a theme that already exists when switching back. Can you avoid adding the theme again?

**Comment by kajetanoss123** [comment] 2020-12-10 08:52
I made it work by adding
`ngOnDestroy() {
        Blockly.registry.unregister('theme', 'themename');
    }`

**Comment by roroettg** [comment] 2020-12-10 09:24
Good solution. I might add this to the documentation.

I will close this for now.

**Closed as completed by roroettg** 2020-12-10 09:24 UTC
Labels: bug
